joint_states: /joint_states

cameras:
  # RealSense D435 chest camera serial mapping:
  #   chest: 332322072253
  chest: /chest_camera/color/image_raw
  # RealSense D435 wrist camera serial mapping:
  #   left_wrist: 317222072848
  #   right_wrist: 327122079310
  left_wrist: /left_wrist_camera/color/image_raw
  right_wrist: /right_wrist_camera/color/image_raw

actions:
  left_arm: /left_forward_position_controller/commands
  right_arm: /right_forward_position_controller/commands
  left_gripper: /left_gripper_controller/joint_trajectory
  right_gripper: /right_gripper_controller/joint_trajectory
